name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  setup:
    name: Setup Go
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'

      - name: Run tests
        run: go test ./...

  simple:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        env:
          env_secret: ${{secrets.MY_WORKFLOW_SECRET}}
        run: echo "$env_secret"

  make_string:
    runs-on: ubuntu-latest
    
    outputs:
      my_output: ${{steps.my_step.outputs.my_string}}
    
    steps:
      - id: my_step
        run: echo "my_string=Hello World" >> "$GITHUB_OUTPUT"

  last_job:
    runs-on: ubuntu-latest
    
    needs: make_string

    strategy:
      matrix:
        nums: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]   
 
    steps:
      - env:
          MY_OUTPUT: ${{needs.make_string.outputs.my_output}}
          NUM: ${{matrix.nums}}
        run: |
          echo "$MY_OUTPUT - $NUM"
